# Generated by Django 3.2.25 on 2024-08-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HenaaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
