# Generated by Django 2.2.4 on 2024-08-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HenaaApp', '0002_auto_20240807_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_pw',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
