# Generated by Django 3.2.25 on 2024-08-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HenaaApp', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_orders', to='HenaaApp.user'),
        ),
    ]
